from enum import Enum

class UserArchetype(str, Enum):
    SALES_HIGH_INTENT = "SALES_HIGH_INTENT"
    SALES_WINDOW_SHOPPER = "SALES_WINDOW_SHOPPER"
    SALES_PROBLEM_SOLVER = "SALES_PROBLEM_SOLVER"
    B2B_ENTERPRISE = "B2B_ENTERPRISE"
    POST_SALE_SUPPORT = "POST_SALE_SUPPORT"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    OUT_OF_DOMAIN = "OUT_OF_DOMAIN"
    MALICIOUS_ADVERSARIAL = "MALICIOUS_ADVERSARIAL"
    GENERAL_GREETING = "GENERAL_GREETING"
    CONTEXTUAL_REWARM = "CONTEXTUAL_REWARM"
